package com.sucharita.JiraApi;

public class JiraConfig {

	public static final String BASE_URL = "https://sucharitas.atlassian.net";
	public static final String TOKEN = "Basic c2Vuc3VjaGFyaXRhMTVAZ21haWwuY29tOkFUQVRUM3hGZkdGMFRSV1FOWGxQQm53anhIc1M3bnZIVTlYd0dhTkN0YmNGYlFJS0t5bmV2aDlvSlo5Y2V3VFBiS0pnZG0wODJOcXVOM3VhU1hKa3Q1WDc3QlFLUzNVOGxKNGJmWV9qNWFXaFNPa0hhZnZZOWNvdmwxZ1lYUl9JOWk3VE4xcVBsei10eWIxUE80bV93X0lMN2tyZTBycnQwdWNTOS1ZdkJvVzJaMnc0dXlZRGZfMD0xQ0Q1MjcwMw==";

}
